# comprehension

In [3]:
lst = []
n = int(input('enter the number of times you want to input'))
for i in range(n):
    lst.append(int(input('enter a number')))
print(lst)

enter the number of times you want to input3
enter a number1
enter a number2
enter a number3
[1, 2, 3]


In [9]:
lst = []
n = int(input('enter the number of times you want to input'))
lst = [int(input('enter a number'))for i in range(n)]
print(lst)

enter the number of times you want to input3
enter a number3
enter a number2
enter a number4
[3, 2, 4]


In [10]:
square_list = []
for x in range(1,10):
    square_list.append(x**2)
print(square_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [11]:
square_list = []
square_list = [x**2 for x in range(1,10)]
print(square_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [14]:
paragraph = ["There was a fox", "It was brown in colour."," It was seen last time yesterday"]
wordlist = []
for sentence in paragraph:
    for word in sentence.split():
        wordlist.append(word)
print(wordlist)
        

['There', 'was', 'a', 'fox', 'It', 'was', 'brown', 'in', 'colour.', 'It', 'was', 'seen', 'last', 'time', 'yesterday']


In [16]:
wordlist = [word for sentence in paragraph for word in sentence.split() ]
print(wordlist)

['There', 'was', 'a', 'fox', 'It', 'was', 'brown', 'in', 'colour.', 'It', 'was', 'seen', 'last', 'time', 'yesterday']


In [17]:
vowels = ['a','e','i','o','u']
for i in vowels:
    print(i)

a
e
i
o
u


In [18]:
print(i) for i in vowels


SyntaxError: invalid syntax (<ipython-input-18-b056ebe28849>, line 1)

In [21]:
paragraph = ["There was a fox", "It was brown in colour."," It was seen last time yesterday"]
vowels = ['a','e','i','o','u']
newlist = []
for sentence in paragraph:
    for word in sentence:
        for letter in word:
            if letter in vowels:
                newlist.append(letter)
print(newlist)    
print(set(newlist))
        

['e', 'e', 'a', 'a', 'o', 'a', 'o', 'i', 'o', 'o', 'u', 'a', 'e', 'e', 'a', 'i', 'e', 'e', 'e', 'a']
{'o', 'e', 'u', 'i', 'a'}


In [23]:
paragraph = ["There was a fox", "It was brown in colour."," It was seen last time yesterday"]
vowels = ['a','e','i','o','u']
newlist = []
newlist = [letter for sentence in paragraph for word in sentence for letter in word if letter in vowels ]
print(newlist)
print(set(newlist))

['e', 'e', 'a', 'a', 'o', 'a', 'o', 'i', 'o', 'o', 'u', 'a', 'e', 'e', 'a', 'i', 'e', 'e', 'e', 'a']
{'o', 'e', 'u', 'i', 'a'}


# NUMPY

In [24]:
#enables working with arrays and for scientific computing
#Basic numpy object is nd array or n dimensional array
"""nd array need to be homogenous array
data type need to be the same. We usually keep int or float to work with numpy

Why we need numpy when we have list in python: because numpy is very fast and the computing is very convinient
Everything runs with respect to c programming

in a list python use for loop to check one by one but numpy do the opertion in a parallel manner.Numpy also use 
very less storage space"""
""" lets explore the numpy package practically"""


' lets explore the numpy package practically'

In [25]:
#lets perform some numpy operation
import numpy as np

In [27]:
a=np.array([1,2,3])

In [28]:
print(a)

[1 2 3]


In [35]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
b.shape

(2, 4)

In [41]:
type(b)

numpy.ndarray

In [42]:
b.dtype

dtype('int32')

In [49]:
import numpy as np
a = np.array([[1,2,3], ['a','b','c'], [5,6,7]])
print(a)
type(a)
print(a.shape)

[['1' '2' '3']
 ['a' 'b' 'c']
 ['5' '6' '7']]
(3, 3)


In [63]:
#lets print 1 to 100 using numpy
import numpy as np
a=np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [75]:
c = range(10000)
%timeit [i**3 for i in c]

2.21 ms ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [88]:

a = np.arange(10000)
%timeit a**3


18 µs ± 168 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [89]:
l1 = range(10000)
l2 = [i**2 for i in range (10000)]

In [90]:
%timeit list (map(lambda x,y: x*y, l1, l2))

985 µs ± 5.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [91]:
a1 = np.array(l1)
b1 = np.array(l2)

In [92]:
%timeit a1*b1

6.32 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [93]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [98]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [99]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
np.full((5,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [113]:
np.full((3,3),2.2, dtype = np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [118]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [119]:
v = np.array([1,2,3])

In [120]:
v

array([1, 2, 3])

In [127]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [135]:
50*np.random.random()+2

2.462767656669155

In [143]:
np.random.random([4,4])

array([[0.92815921, 0.1027579 , 0.74337081, 0.12414775],
       [0.82398954, 0.20920831, 0.10035041, 0.15592905],
       [0.06246649, 0.94393776, 0.61641691, 0.2411792 ],
       [0.4147428 , 0.12072298, 0.64334657, 0.52519897]])

In [146]:
a = np.linspace(1,50,100)
print(a)

[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909 41.

In [147]:
a.itemsize

8

In [148]:
b = np.arange(18)

In [149]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [150]:
b.itemsize

4

In [151]:
b =np.arange(18).reshape(2,3,3)

In [152]:
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [154]:
b.shape

(2, 3, 3)

In [156]:
a=np.array([2,4,6,8,10])

In [157]:
print(a)

[ 2  4  6  8 10]


In [163]:
print(a[:2])

[2 4]


In [172]:
print(b[1][1][[0]])

[12]


In [173]:
b>2

array([[[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [174]:
b[(b>2)&(b<10)]

array([3, 4, 5, 6, 7, 8, 9])

In [175]:
a = ([0,1,2,3,4,5,6,7,8,9])


In [176]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [177]:
b= a

In [178]:
b[0]=11

In [179]:
a

[11, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [180]:
b

[11, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [182]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[1,2,3]])

In [184]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 2 3]]


In [185]:
a==b

array([[False, False, False],
       [False, False, False]])

In [186]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [187]:
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3]])

In [189]:
np.vstack((b,a))

array([[7, 8, 9],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [194]:
for i in a:
    for x in i:
        print(x, end = " ")

1 2 3 4 5 6 

In [196]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [197]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [198]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [199]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [200]:
np.sum(a)

190

In [202]:
np.median(a)

9.5

In [204]:
np.std(a)

5.766281297335398

In [206]:
np.sum(np.sin(a))

0.08527663369215396

In [207]:
np.sum(np.exp(a))

282354842.13022625

In [208]:
a = np.arange(1,10).reshape(3,3)

In [209]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [212]:
np.linalg.det(a)

-9.51619735392994e-16

In [213]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [215]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [216]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [219]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [229]:
b = np.array([[11,12,13],[14,15,16],[17,18,19]])
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [228]:
np.dot(a,b)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [232]:
#change data types in array
a = np.array([1,1,0], dtype=bool)
print(a)

[ True  True False]


In [234]:
b = np.array([0,1,1], dtype = bool)
print(b)

[False  True  True]


In [236]:
c = np.array([2,3,4], dtype = float)
print(c)

[2. 3. 4.]


In [237]:
d = np.array([5,6,7], dtype = bool)

In [238]:
print(d)

[ True  True  True]


In [239]:
np.logical_or(a,b)

array([ True,  True,  True])

In [240]:
np.logical_and(b,c)

array([False,  True,  True])

In [242]:
np.all(a==a)

True

In [243]:
a = np.array([[2,3],[3,4],[5,6]])

In [244]:
print(a)

[[2 3]
 [3 4]
 [5 6]]


In [247]:
a.sum(axis = 1)

array([ 5,  7, 11])

In [250]:
a.max(axis = 1)

array([3, 4, 6])

In [251]:
a.argmax()

5

In [253]:
a.shape

(3, 2)

In [256]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [257]:
a.shape

(10,)

In [258]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
a[:, np.newaxis].shape

(10, 1)